AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Project:
    Type: String
    Default: "cfn-test-"

Resources:
  WebImage:
    Type: AWS::ECR::Repository
    Properties: 
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete more than 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryName: !Sub "${Project}web-image"

  AppImage:
    Type: AWS::ECR::Repository
    Properties: 
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete more than 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryName: !Sub "${Project}app-image"

Outputs:
  WebImage:
    Value: !Ref WebImage
    Export: { "Name" : !Sub "${Project}ecr-web-image" }
  AppImage:
    Value: !Ref AppImage
    Export: { "Name" : !Sub "${Project}ecr-app-image" }
